spring:
  application:
    name: document-service
  datasource:
    url: jdbc:postgresql://localhost:5432/document_db
    username: document_svc
    password: document_svc
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
server:
  port: 8081
esignflow:
  jwt:
    secret: ${JWT_SECRET:secret}
    expiration: 3600000