name: CI

on:
  pull_request:
    branches:
      - main

  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  document-service:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: services/document-service
    steps:
      - uses: actions/checkout@v4
      - run : chmod +x mvnw
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: maven
      - run: ./mvnw clean verify